; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[base]
monitor_speed = 115200
;upload_protocol = stlink
;debug_tool = stlink
upload_protocol = jlink
debug_tool = jlink
build_type = debug
build_flags =
    -D BLINK_LED=PC13
    -D HAVE_HWSERIAL1
    -D DEBUG_SERIAL=Serial1
    -D L_O_G_DISABLE_THREAD_SAFE
    -D L_O_G_DISABLE_DATE_TIME
    -D L_O_G_LINE_END_CRLF
    -D L_O_G_FOR_MCU
    -D L_O_G_PRINTF=DEBUG_SERIAL.printf
    -D L_O_G_SHOW_DEBUG

[env:stm32_arduino]
extends = base
platform = ststm32
board = genericSTM32F103C8
framework = arduino
build_flags =
    ${base.build_flags}
    -D MAIN_SIMPLE
    -D L_O_G_DISABLE_THREAD_ID

[env:stm32_arduino_freertos]
extends = base
platform = ststm32
board = genericSTM32F103C8
framework = arduino
build_flags =
    ${base.build_flags}
    -D MAIN_FREERTOS
    -D L_O_G_GET_TID_CUSTOM=get_tid
lib_deps =
    stm32duino/STM32duino FreeRTOS @ 10.3.2

[env:stm32_lora_mesh]
extends = base
platform = ststm32
board = genericSTM32F103C8
framework = arduino
build_flags =
    ${base.build_flags}
    -D MAIN_LORA_MESH
    -D L_O_G_DISABLE_THREAD_ID
    -D RADIOLIB_DEBUG_PORT=Serial1
;    -D RADIOLIB_DEBUG
    -D RADIOLIB_DEBUG_BASIC
;    -D RADIOLIB_DEBUG_PROTOCOL
;    -D RADIOLIB_DEBUG_SPI
;    -D RADIOLIB_VERBOSE_ASSERT
lib_deps =
    jgromes/RadioLib @ 7.1.2
